
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-07T16:18:48+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "7de4f55be33e06af21d4418987bd693b31f73a8b",
 "version": "0.6.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
