
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-07T08:48:30+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "30ba4455b1164edb21118a7e0a59501c129a9296",
 "version": "1.15.0.post.dev142"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
