{% set name = "ooipy" %}
{% set version = "1.0.2" %}


package:
  name: {{ ooipy }}
  version: {{ 1.0.2 }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ooipy-{{ version }}.tar.gz
  sha256: 19113741153962f5d8a2c1e331dd7bd6d07b9de54c51a9cb0e9d4d9ae011a7eb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - ooipy
    - ooipy.hydrophone
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ooipy/ooipy
  summary: A python toolbox for acquiring and analyzing Ocean Obvservatories Initiative (OOI) Data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - John Ragland
    - Felix Schwock
