# coding: utf-8

"""
    bmlx api-server.

    Documentation of bmlx api-server apis. To find more info about generating spec from source, please refer to https://goswagger.io/use/spec.html  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import inspect
import pprint
import re  # noqa: F401
import six

from bmlx_openapi_client.configuration import Configuration


class TriggerVersionRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'exp_id': 'int',
        'id': 'int',
        'parameters': 'dict(str, str)',
        'run_name': 'str'
    }

    attribute_map = {
        'exp_id': 'exp_id',
        'id': 'id',
        'parameters': 'parameters',
        'run_name': 'run_name'
    }

    def __init__(self, exp_id=None, id=None, parameters=None, run_name=None, local_vars_configuration=None):  # noqa: E501
        """TriggerVersionRequest - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._exp_id = None
        self._id = None
        self._parameters = None
        self._run_name = None
        self.discriminator = None

        if exp_id is not None:
            self.exp_id = exp_id
        if id is not None:
            self.id = id
        if parameters is not None:
            self.parameters = parameters
        if run_name is not None:
            self.run_name = run_name

    @property
    def exp_id(self):
        """Gets the exp_id of this TriggerVersionRequest.  # noqa: E501


        :return: The exp_id of this TriggerVersionRequest.  # noqa: E501
        :rtype: int
        """
        return self._exp_id

    @exp_id.setter
    def exp_id(self, exp_id):
        """Sets the exp_id of this TriggerVersionRequest.


        :param exp_id: The exp_id of this TriggerVersionRequest.  # noqa: E501
        :type exp_id: int
        """

        self._exp_id = exp_id

    @property
    def id(self):
        """Gets the id of this TriggerVersionRequest.  # noqa: E501


        :return: The id of this TriggerVersionRequest.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TriggerVersionRequest.


        :param id: The id of this TriggerVersionRequest.  # noqa: E501
        :type id: int
        """

        self._id = id

    @property
    def parameters(self):
        """Gets the parameters of this TriggerVersionRequest.  # noqa: E501


        :return: The parameters of this TriggerVersionRequest.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._parameters

    @parameters.setter
    def parameters(self, parameters):
        """Sets the parameters of this TriggerVersionRequest.


        :param parameters: The parameters of this TriggerVersionRequest.  # noqa: E501
        :type parameters: dict(str, str)
        """

        self._parameters = parameters

    @property
    def run_name(self):
        """Gets the run_name of this TriggerVersionRequest.  # noqa: E501


        :return: The run_name of this TriggerVersionRequest.  # noqa: E501
        :rtype: str
        """
        return self._run_name

    @run_name.setter
    def run_name(self, run_name):
        """Sets the run_name of this TriggerVersionRequest.


        :param run_name: The run_name of this TriggerVersionRequest.  # noqa: E501
        :type run_name: str
        """

        self._run_name = run_name

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = inspect.getargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                elif len(args) == 2:
                    return x.to_dict(serialize)
                else:
                    raise ValueError("Invalid argument size of to_dict")
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TriggerVersionRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TriggerVersionRequest):
            return True

        return self.to_dict() != other.to_dict()
