
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-31T21:19:17+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "be1e8eded35d9f3afd640d2942308253afd3bb37",
 "version": "0.0.89.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
