
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-09T11:21:45-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "6a47cb0b20e96ed525d8cf968266b3ffcbf540fa",
 "version": "4.3.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
