
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-07T15:32:04+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "5d8b9602b423ac4831f36a693ffa5cec0af906db",
 "version": "0.9.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
