
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-06T12:35:21+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "c6b8d0525c7dba2293eb3cba7b1f6b556eb73b49",
 "version": "0.9.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
