
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-04T21:41:31+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "aeaf759667836b78f29f4a6eb2295c3b16a9504e",
 "version": "0.0.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
