[tool.poetry]
name = "vigilant-crypto-snatch"
version = "3.0.3"
description = "Crypto currency buying agent"
authors = ["Martin Ueding <mu@martin-ueding.de>"]
license = "MIT"

[tool.poetry.scripts]
vigilant-crypto-snatch = "vigilant_crypto_snatch.cli:main"

[tool.poetry.dependencies]
python = "^3.7.1,<3.10"
requests = "^2.25.1"
sqlalchemy = "^1.3.23"
pyyaml = "^5.4.1"
clikraken = "^0.8.3"
BitstampClient = "^2.2.8"
urllib3 = "^1.26.3"
coloredlogs = "^15.0"
pandas = { version = "^1.2.3", optional = true }
matplotlib = { version = "^3.3.4", optional = true }
tqdm = { version = "^4.59.0", optional = true }
Markdown = { version = "^3.3.4", optional = true }
appdirs = "^1.4.4"
scipy = {version = "^1.6.2", optional = true}

[tool.poetry.extras]
evaluation = ["pandas", "matplotlib", "tqdm", "Markdown", "scipy"]

[tool.poetry.dev-dependencies]
mkdocs_material = "^7.0.5"
pytest = "^6.2.2"
black = "^20.8b1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
