[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "toc2audio"
author = "Jesús Cea Avión"
author-email = "jcea@jcea.es"
home-page = "https://www.jcea.es/"
requires-python = ">=3.6"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "License :: OSI Approved :: GNU Affero General Public License v3",
    "Topic :: Multimedia :: Sound/Audio :: Editors",
]
