#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup


setup(name='toc2audio',
      version='0.0.0',
      description='Add Table of Contents and chapters to audio files',
      author='Jesús Cea Avión',
      author_email='jcea@jcea.es',
      url='https://www.jcea.es/',
      py_modules=['toc2audio'],
      python_requires='>=3.6',
     )
