[tool.poetry]
name = "run_once"
version = "0.1.0"
description = ""
authors = ["Daeyun Shin <daeyuns@uci.edu>"]
license = "MIT"
#exclude = ["**"]
include = [
    "run_once.py",
    "generated/proto/*.py",
]

[tool.poetry.dependencies]
python = "^3.6"
grpcio = "^1.15"
grpcio-tools = "^1.15"
joblib = "^1.0.1"

[tool.poetry.dev-dependencies]
pytest = ">=5"
numpy = ">=1.0"
psutil = "^5"
black = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79
