
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "cf81c63a70ce2a2cc7fbdea846fb293b678145b0",
 "version": "0.21.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
