
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-10T17:28:58+0800",
 "dirty": true,
 "error": null,
 "full-revisionid": "70ddd09b68698b8f6214b77e95bf623eb0fe4011",
 "version": "0.0.90.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
