[tool.poetry]
name = "pseudonymize-pdf"
version = "0.2.0"
description = "A convenience library to read and alter PDFs to remove personally identifying data"
authors = ["Stephen Badger <stephen.badger@vitalbeats.com>"]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^6.2.3"
pytest-cov = "^2.11.1"
pycodestyle = "^2.7.0"
autopep8 = "^1.5.6"
pylint = "^2.7.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
