#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['trailrunner', 'trailrunner.tests']

package_data = \
{'': ['*']}

setup(name='trailrunner',
      version='0',
      description='Run things on paths',
      author='John Reese',
      author_email='john@noswap.com',
      url='https://github.com/jreese/trailrunner',
      packages=packages,
      package_data=package_data,
      python_requires='>=3.6',
     )
