# Generated by Django 3.1.8 on 2021-04-10 10:45

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailphotovoter', '0007_auto_20210224_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='votinghelp',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='allow_same_points',
            field=models.BooleanField(default=False),
        ),
    ]