#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup


setup(name='infixed',
      version='0.0.1',
      description='Provides `make_infix` to create custom infix classes and multiple premade infix classes.',
      author='Pradhyum R',
      author_email='drpradhyum2016@outlook.com',
      url='https://github.com/techieji/infixed',
      py_modules=['infixed'],
     )
