# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"GenFileFormat": "01_datasets_genetic_dataset.ipynb",
         "OVPDataSetError": "02_datasets_OVPDataset.ipynb",
         "parse_class": "02_datasets_OVPDataset.ipynb",
         "OVPDataset": "02_datasets_OVPDataset.ipynb",
         "SampleFileFormat": "03_datasets_sample_file.ipynb",
         "RsidComboInfo": "04_odds_ratio.ipynb",
         "get_geno_combination_df": "04_odds_ratio.ipynb",
         "CombinedGenoPheno": "05_datasets_CombinedGenoPheno.ipynb",
         "conf_loader": "catalog.ipynb",
         "conf_test_data_catalog": "catalog.ipynb",
         "test_data_catalog": "catalog.ipynb",
         "cd": "catalog.ipynb",
         "change_cwd_dir": "catalog.ipynb",
         "get_config": "catalog.ipynb",
         "get_catalog": "catalog.ipynb",
         "reload_catalog": "catalog.ipynb",
         "reload": "catalog.ipynb",
         "package_outer_folder": "catalog.ipynb",
         "get_possible_geno_combinations": "datasets_genetic_file.ipynb",
         "get_geno_one_snp": "datasets_bgen_file_format.ipynb",
         "BgenFileObject": "datasets_bgen_file_format.ipynb",
         "BgenFileFormat": "datasets_bgen_file_format.ipynb",
         "GeneticFileFormat": "datasets_genetic_file.ipynb",
         "row_vectorize": "datasets_genetic_file.ipynb",
         "triplicate_converter": "datasets_genetic_file.ipynb",
         "SingleFilePathSchema": "datasets_schemas.ipynb",
         "MultipleFilePathSchema": "datasets_schemas.ipynb",
         "CaseControlFilePathSchema": "datasets_schemas.ipynb"}

modules = ["datasets/genetic_file/Gen.py",
           "datasets/OVPDataset.py",
           "datasets/sample_file.py",
           "odds_ratio.py",
           "datasets/CombinedGenoPheno.py",
           "datasets/utils.py",
           "catalog.py",
           "datasets/genetic_file/Bgen.py",
           "datasets/genetic_file/__init__.py",
           "datasets/schemas.py"]

doc_url = "https://corradin-lab.github.io #https://pages.github.corradin-lab.com./corradin_ovp_utils/"

git_url = "https://github.com/corradin-lab/corradin_ovp_utils/tree/master/ #https://github.com/hoangthienan95/corradin_ovp_utils/tree/master/"

def custom_doc_links(name): return None
