[tool.poetry]
name = "chaoxing"
version = "0.1.1"
description = ""
authors = ["lisonge <i@songe.li>"]

[tool.poetry.dependencies]
python = "^3.8"
httpx = "^0.17.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
autopep8 = "^1.5.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
