
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-04T15:08:30+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "40f1b73f880cf9b1752dfaf95c6dae5c131f547c",
 "version": "0.4.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
