[tool.poetry]
name = "log-with-context"
version = "0.1.0"
description = ""
authors = ["James Mishra <james.mishra@neocrym.com>"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
isort = "^5.8.0"
mypy = "^0.812"
black = "^20.8b1"
pylint = "^2.7.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
