
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-31T15:18:35-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "bf69bef00b5c2b7664781539ade06a239d7b1e39",
 "version": "2.8.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
