
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-08T16:31:36-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "6e197e0771945854e99cd042e9ec43ef04ce7542",
 "version": "0.9.44"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
