[tool.poetry]
name = "autodoc_pydantic"
version = "0.1.1"
description = "Seamlessly integrate pydantic models in your Sphinx documentation."
authors = ["mansenfranzen <franz.woellert@gmail.com>"]
packages = [{ include = "sphinxcontrib" }]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/mansenfranzen/autodoc_pydantic"
repository = "https://github.com/mansenfranzen/autodoc_pydantic"
documentation = "https://github.com/mansenfranzen/autodoc_pydantic"
keywords = ["sphinx", "pydantic", "autodoc", "documentation", "extension"]
classifiers = [
    "Framework :: Sphinx :: Extension",
    "Topic :: Documentation :: Sphinx",
    "Topic :: Software Development :: Documentation"
]

[tool.poetry.dependencies]
python = ">=3.6.1"
Sphinx = ">=3.0"
pydantic = ">=1.0"

[tool.poetry.dev-dependencies]
pytest = "^6.0"
pytest-cov = "^2.0"
sphinx-rtd-theme = "^0.5.1"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--cov-report term --cov-report xml:coverage.xml --cov=sphinxcontrib"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
