
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-07T21:48:43-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "86f20c0af6f97b039e5d029884609c8eee30b17b",
 "version": "0.3.29"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
