
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "eb5ddbadc0517913556479a42d0bab362f61e56f",
 "version": "2430"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
