
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-12T07:52:45+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "af81b482f5a6416a134b5e68948a551840735e2a",
 "version": "0.7.0.post.dev56"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
