
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-11T09:55:07+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d0959f0affd2089c4cc439e1ba2b83acc3f71e71",
 "version": "0.8.3b0.dev202104120707"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
