{% set name = "bcolz-zipline" %}
{% set version = "1.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f04a15ecc312c91604d463a3e64f9f64b2623b766bc03fc4f7b159d8f2e71856

build:
  number: 0
#  script: {{ PYTHON }} -m pip install . -vv # [ linux or win ]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - numpy
    - setuptools_scm
    - build # [ osx64]
  run:
    - python
    - numpy

test:
  commands:
    - python -c "import bcolz;bcolz.test()"
  requires:
    - numpy

about:
  home: https://github.com/stefan-jansen/bcolz-zipline
  summary: Columnar and compressed data containers.
  license: BSD-1-Clause
  license_file: LICENSES/BCOLZ.txt
