
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-12T12:14:08+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f0f65ba0e1768615dc72a327f21c033a39937189",
 "version": "0.4.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
