
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-07T10:33:22+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e46563ff5edb7bd11081cd1a9cdef6e1a8e9f4e7",
 "version": "v0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
