
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-06T16:09:16+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "15f014ffa2a749c412a78fdbcfdeb55ba3653cd2",
 "version": "0.29.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
