
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-04T11:38:19-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "b15f69b4f696be627afc07f1d86f3048cfe282ee",
 "version": "2.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
