
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-09T08:45:30+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "faa7821d204e8818199ac467f405b857aab18d7c",
 "version": "2431"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
