# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"code_cell": "00_convert.ipynb",
         "write_module_cell": "00_convert.ipynb",
         "init_nb": "00_convert.ipynb",
         "write_cell": "00_convert.ipynb",
         "write_nb": "00_convert.ipynb",
         "generate_settings": "00_convert.ipynb",
         "generate_actions": "00_convert.ipynb",
         "convert_lib": "00_convert.ipynb"}

modules = ["convert.py"]

doc_url = "https://Novetta.github.io/lib2nbdev/"

git_url = "https://github.com/Novetta/lib2nbdev/tree/main/"

def custom_doc_links(name): return None
