
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-07T09:13:00+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "903c1ec37c40e8be012af0c10629951d32892865",
 "version": "1.15.0.post.dev144"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
