
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-09T03:20:30+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "9ddabbe47404935eb43233c7f965459e3757c05d",
 "version": "1.15.0.post.dev154"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
