
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-07T05:06:46+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "3a382367b2170ce592a02c487047a4a329140d2b",
 "version": "1.15.0.post.dev138"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
