
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-12T16:52:49-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "d133254d7c57bf71a8323c8c812b79a65baf5640",
 "version": "0.3.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
