
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-06T22:12:35+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "98f052206a17091352bd153d63e3de482a5420ca",
 "version": "1.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
