#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['podsearch_ai']

package_data = \
{'': ['*']}

setup(name='podsearch_ai',
      version='0.2.0',
      description="Let's find some podcasts!",
      author='Hang Li',
      author_email='bitlihang@gmail.com',
      url='https://github.com/hangligit/podsearch_ai-py',
      packages=packages,
      package_data=package_data,
      python_requires='>=3.7',
     )
