# Generated by Django 3.1.7 on 2021-04-08 17:43

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_verify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='debug_headers',
        ),
        migrations.RemoveField(
            model_name='service',
            name='debug_parameters',
        ),
        migrations.RemoveField(
            model_name='service',
            name='debug_url',
        ),
        migrations.AddField(
            model_name='service',
            name='accepted_codes',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(400, 400), (401, 401), (402, 402), (403, 403), (404, 404), (405, 405), (406, 406), (407, 407), (408, 408), (409, 409), (410, 410), (411, 411), (412, 412), (413, 413), (414, 414), (415, 415), (416, 416), (417, 417), (418, 418), (421, 421), (422, 422), (423, 423), (424, 424), (425, 425), (426, 426), (428, 428), (429, 429), (431, 431), (444, 444), (449, 449), (450, 450), (451, 451), (499, 499), (500, 500), (501, 501), (502, 502), (503, 503), (504, 504), (505, 505), (506, 506), (507, 507), (509, 509), (510, 510), (511, 511)], default=None, max_length=175),
        ),
        migrations.AddField(
            model_name='service',
            name='rejected_codes',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(100, 100), (101, 101), (102, 102), (103, 103), (122, 122), (200, 200), (201, 201), (202, 202), (203, 203), (204, 204), (205, 205), (206, 206), (207, 207), (208, 208), (226, 226), (300, 300), (301, 301), (302, 302), (303, 303), (304, 304), (305, 305), (306, 306), (307, 307), (308, 308)], default=None, max_length=95),
        ),
        migrations.AlterField(
            model_name='service',
            name='method',
            field=models.CharField(choices=[('delete', 'delete'), ('get', 'get'), ('post', 'post'), ('patch', 'patch'), ('put', 'put')], default='get', max_length=20),
        ),
    ]
