#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

install_requires = \
['typer[all] == 0.3.2', 'humanize == 3.3.0']

entry_points = \
{'console_scripts': ['dcp = dcp:main']}

setup(name='dcp',
      version='1.0.0',
      description='Command line utility for coping of files and folders via python bypassing system call.',
      author='baterflyrity',
      author_email='baterflyrity@yandex.ru',
      url='https://github.com/baterflyrity/dcp',
      py_modules=['dcp'],
      install_requires=install_requires,
      entry_points=entry_points,
      python_requires='~=3.8',
     )
