[tool.poetry]
name = "vwrt"
version = "0.0.1"
description = "Video Waste Reduction Tool: Automated video editing"
authors = ["Evan Binder <evanmbinder@gmail.com>"]
license = "MIT"
repository = "https://github.com/evnb/vwrt"
keywords = ["Ffmpeg", "Accessibility", "Video Editing", "YouTube"]
classifiers = [
	"Topic :: Multimedia :: Video",
	"Topic :: Multimedia :: Sound/Audio",
	"Topic :: Multimedia",
	"Topic :: Utilities",
	"Environment :: Console",
	"Intended Audience :: Education",
	"Intended Audience :: End Users/Desktop"
]

[tool.poetry.dependencies]
python = "^3.6"
numpy = "~1.19.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
vwrt = "vwrt.vwrt:main"