
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-06T16:01:18-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "ac22af29d8c8cd9f1bb57a4ff5ff0cc53ba8aa1b",
 "version": "0.9.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
