
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-05T15:03:20+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "aae98f1aeee42a49f15d58b0c7a947414edeedba",
 "version": "1.0.4rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
