
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-12T15:12:24+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "fe522aab7808a70b450ed6d52c474faf431f4ff3",
 "version": "1.6.0b3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
