
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-06T14:48:28+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "4dd3f2ae4c50280e02447fdc6cd5189230fbf7cd",
 "version": "2021.04.07"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
