
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-05T15:11:33-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "d7bcc2e48925f59fc7fa13c6a80aeec51fccbd95",
 "version": "0.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
