[tool.poetry]
authors = ["Leon Bowie <leon@bowie-co.nz>"]
description = "Asyncpixel"
documentation = "https://aiomcstats.readthedocs.io"
homepage = "https://github.com/Obsidion-dev/aiomcstats"
license = "GPL-3.0-or-later"
name = "aiomcstats"
readme = "README.md"
repository = "https://github.com/Obsidion-dev/aiomcstats"
version = "0.1.3"

[tool.poetry.dependencies]
dnspython = "^2.1.0"
pydantic = "^1.7.3"
python = "^3.8"
asyncio-dgram = "^1.2.0"

[tool.poetry.dev-dependencies]
Pygments = "^2.7.4"
Sphinx = "^3.5.3"
black = "^20.8b1"
coverage = {extras = ["toml"], version = "^5.4"}
darglint = "^1.8.0"
flake8 = "^3.8.4"
flake8-bandit = "^2.1.2"
flake8-bugbear = "^21.3.2"
flake8-docstrings = "^1.6.0"
mypy = "^0.812"
pep8-naming = "^0.11.1"
pre-commit = "^2.10.1"
pre-commit-hooks = "^3.4.0"
pytest = "^6.2.3"
reorder-python-imports = "^2.4.0"
safety = "^1.10.3"
sphinx-autobuild = "^2021.3.14"
sphinx-rtd-theme = "^0.5.2"
sphinxcontrib-napoleon = "^0.7"
typeguard = "^2.11.1"
nox = "^2020.12.31"
nox-poetry = "^0.8.4"

[tool.poetry.urls]
Changelog = "https://github.com/Obsidion-dev/aiomcstats/releases"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry>=1.1.0"]
