
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2021-04-05T19:44:54-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "f95fc9a8ace2c1a40bdacae5518c10bdec5025e6",
 "version": "2.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
