name: tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    name: "${{ matrix.pymc-version }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - pymc-version: "pymc3==3.9.3"
            arviz-version: "arviz==0.11.1"
          - pymc-version: "pymc3==3.10"
            arviz-version: "arviz==0.11.1"
          - pymc-version: "pymc3==3.11"
            arviz-version: ""
          - pymc-version: "https://github.com/pymc-devs/pymc3/archive/master.zip"
            arviz-version: ""

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - uses: actions/cache@v2
        with:
          path: ~/.theano
          key: ${{ runner.os }}-${{ matrix.pymc-version }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.pymc-version }}-

      - name: Set up Python
        id: setup_python
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: starry_process
          environment-file: environment.yml

      - name: Install dependencies
        id: install
        if: steps.setup_python.outcome == 'success'
        shell: bash -l {0}
        run: |
          python -m pip install -U pip
          python -m pip install ${{ matrix.pymc-version }} ${{ matrix.arviz-version }}
          python -m pip install -e ".[app,tests]"

      - name: Run tests
        if: steps.install.outcome == 'success'
        shell: bash -l {0}
        run: python -m pytest -v tests --junitxml=junit/test-results.xml

      - name: Get unique id
        id: unique-id
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: |
          export JOB_ID=`echo $STRATEGY_CONTEXT | md5sum`
          echo "::set-output name=id::$JOB_ID"

      - uses: actions/upload-artifact@v2
        with:
          name: test-results-${{ steps.unique-id.outputs.id }}
          path: junit/test-*.xml
