
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-09T14:45:12+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "146f46c888f1b6dd99d74bd3703daf9e9ce529d1",
 "version": "0.12.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
