
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-12T10:52:11+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f86b3171534a4bccb2487efc039941fd75dcda7a",
 "version": "0.7.0.post.dev64"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
