
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-05T00:32:36-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "e55e297b6b6bc7276324038518e8524d07c4742b",
 "version": "2.0.0rc4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
