# -*- coding: utf-8 -*-
"""__init__.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ilsuC0dLNKpKmBZkIc62Jg49NmpGym3w
"""

def coolprint():
    print("This is UAmerica :)")

def addition(x,y):
    return x + y