# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from action_pb2 import (
    ActionInvocationStatusValue as action_pb2___ActionInvocationStatusValue,
    ActionParams as action_pb2___ActionParams,
    ThirdPartyActionInvocationResponse as action_pb2___ThirdPartyActionInvocationResponse,
)

from entity_pb2 import (
    Entity as entity_pb2___Entity,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class GetActionsRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    def __init__(self,
        ) -> None: ...
type___GetActionsRequest = GetActionsRequest

class GetActionsResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def actions(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[entity_pb2___Entity]: ...

    def __init__(self,
        *,
        actions : typing___Optional[typing___Iterable[entity_pb2___Entity]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"actions",b"actions"]) -> None: ...
type___GetActionsResponse = GetActionsResponse

class InvokeActionRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    entity_canonical_id: typing___Text = ...

    @property
    def action_config(self) -> entity_pb2___Entity: ...

    @property
    def override_action_params(self) -> action_pb2___ActionParams: ...

    def __init__(self,
        *,
        action_config : typing___Optional[entity_pb2___Entity] = None,
        override_action_params : typing___Optional[action_pb2___ActionParams] = None,
        entity_canonical_id : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"action_config",b"action_config",u"override_action_params",b"override_action_params"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"action_config",b"action_config",u"entity_canonical_id",b"entity_canonical_id",u"override_action_params",b"override_action_params"]) -> None: ...
type___InvokeActionRequest = InvokeActionRequest

class InvokeActionResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    action_status: action_pb2___ActionInvocationStatusValue = ...

    @property
    def raw(self) -> action_pb2___ThirdPartyActionInvocationResponse: ...

    def __init__(self,
        *,
        action_status : typing___Optional[action_pb2___ActionInvocationStatusValue] = None,
        raw : typing___Optional[action_pb2___ThirdPartyActionInvocationResponse] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"raw",b"raw"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"action_status",b"action_status",u"raw",b"raw"]) -> None: ...
type___InvokeActionResponse = InvokeActionResponse
