#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['sqimple']

package_data = \
{'': ['*'], 'sqimple': ['static/*', 'templates/*']}

install_requires = \
['Flask==1.1', 'waitress==2.0']

entry_points = \
{'console_scripts': ['sqimple = sqimple.main:main']}

setup(name='sqimple',
      version='0.0.7',
      description='Simple SQL Web Interface',
      author='Zach Gulde',
      author_email='zachgulde@gmail.com',
      url=None,
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      entry_points=entry_points,
     )
