[tool.poetry]
name = "pytorch-polkadots"
version = "0.1.1"
description = "Provides the ability to construct a simulated image dataset on the fly with different characteristics."
authors = ["Fabien  Campagne <fac2003@gmail.com>"]

license = "MIT"
readme = "README.md"
homepage = "https://github.com/fac2003/pytorch_polkadots"
repository = "https://github.com/fac2003/pytorch_polkadots"
keywords = ["machine learning", "simulated datasets", "images"]
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Development Status :: 4 - Beta",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Operating System :: OS Independent",
]
include = [
    "LICENSE.txt",
]

[tool.poetry.dependencies]
python = "^3.7"
Pillow = "^8.1.2"
torch = "^1.8.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
