[tool.poetry]
name = "weather_for_prebas_1"
version = "0.1.0"
description = ""
authors = ["Jan Pisl <jan.pisl@simosol.fi>"]

[tool.poetry.dependencies]
python = "^3.6"
geopandas = "^0.9.0"
utm = "^0.7.0"
requests = "^2.25.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
