
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-06T15:19:55-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "c8dab5e18f98114fa45ae1c0f85ecef505d81bcc",
 "version": "0.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
