
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-09T12:10:54+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "5902befd52417928f7471394895d9019fd606930",
 "version": "2433"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
