[tool.poetry]
name = "PyDockExp2"
version = "0.1.0"
description = "A simple random matrix generato"
authors = ["lmriccardo <absintio098@gmail.com>"]
license = "MIT"
repository = "https://github.com/lmriccardo/PyDocker"

[tool.poetry.dependencies]
python = "^3.9"
matplotlib = "^3.4.1"
numpy = "^1.20.2"
pandas = "^1.2.3"
rich = "^10.1.0"
tqdm = "^4.60.0"
coloredlogs = "^15.0"
colorama = "^0.4.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
