
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-12T20:17:41+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "e5adb1f118cc1cae33036f3df7463887edc46ceb",
 "version": "0.0.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
