
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-09T12:03:18+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f2d3c3831173d6c28d753ed3d75b8ed41fd54d2e",
 "version": "2432"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
