
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-07T15:06:18-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "1a1f3c7fc1e1b83b6880de61265d166c9cdbe42c",
 "version": "v1.0.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
