
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-12T03:19:08+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b92a2a254366dc3fa2c832e4305ffe5542d33268",
 "version": "1.15.0.post.dev158"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
