#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup


setup(name='uibbq',
      version='1.0',
      description='Micropython iBBQ Interface',
      author='James Cooke',
      author_email='uibbq@jaynne.co.uk',
      url='https://github.com/cookejames/uibbq',
      py_modules=['uibbq'],
     )
