[tool.poetry]
name = "yfbasic"
version = "0.2.0"
description = "Thin python wrapper to retrieve and work with Yahoo! finance data"
authors = ["jens <jens.v.han@protonmail.com>"]
repository = "https://gitlab.com/jensusius/yfbasic"
readme = "README.md"
keywords = ["yahoo", "finance", "stocks", "investment"]

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^1.8.1"
requests = "^2.25.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^20.8b1"
isort = "^5.8.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
multi_line_output = 3