[tool.poetry]
name = "python-lbp3"
version = "0.1.0"
description = "A Python API wrapper for the LBP3 datastore"
authors = ["Matt Gosden <mdgosden@gmail.com>"]
exclude = ["docs", "app", "analysis", "notebooks", "lib"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.6,<4.0"
httpx = "^0.17.*"
backoff = "^1.10.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.3"
pylint = "^2.7.4"
black = "^20.8b1"
nb-black = "^1.0.7"
jupyter = "^1.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
