[tool.poetry]
name = "Desigz"
version = "1.0.0"
description = "Modern Graphic Library"
authors = ["6IXK1LL <jxpkaxyz@gmail.com>"]

[tool.poetry.dependencies]
python = "3.9.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
