
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-06T04:05:02-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "ddc67112479c234ff1e0d7054a7f8b105fc32775",
 "version": "4.1.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
