
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-05T14:03:13-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "e8565f5e65809e1d9fc5a8d182e52c3c03bbeea8",
 "version": "0.1.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
