#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['wrapped']

package_data = \
{'': ['*']}

setup(name='wrapped',
      version='0.1.0',
      description='Python wrappers for useful R functions.',
      author='Vivek Gopalakrishnan',
      author_email='vgopala4@jh.edu',
      url='https://v715.github.io',
      packages=packages,
      package_data=package_data,
     )
