
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-12T05:29:56+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "3bdbaa5ebe4aefa69150eb41fa70bed35c3b727c",
 "version": "0.7.0.post.dev54"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
