[tool.poetry]
name = "truechecker"
version = "2021.4.5"
description = "Python client for True Checker API"
authors = ["Oleg A. <oleg@trueweb.app>"]
maintainers = ["Oleg A. <oleg@trueweb.app>"]
license = "MIT"
readme = "README.md"
homepage = ""
repository = "https://gitlab.com/true-web-app/true-checker/true-checker-python"
documentation = "https://checker.trueweb.app/redoc/"
keywords = [
    "True Checker",
    "Telegram",
    "Bots",
]


[tool.poetry.dependencies]
python = "^3.8"
aiohttp = "~3.7"
certifi = "^2020.12.5"
ujson = [
    { version = "~4.0", platform = "linux" },
    { version = "~4.0", platform = "darwin" },
]
uvloop = [
    { version = "~0.15", platform = "linux" },
    { version = "~0.15", platform = "darwin" },
]
ciso8601 = { version = "~2.1", platform = "linux" }
pydantic = "^1.8.1"


[tool.poetry.dev-dependencies]
black = "20.8b1"
flake8 = "*"
isort = "*"
mypy = "*"
pytest = "^6.2.3"
pytest-asyncio = "^0.14.0"
coverage = "^5.5"
aresponses = "^2.1.4"
pre-commit = "^2.11.1"

[tool.black]
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.pytest_cache
  | \.tox
  | venv
  | build
  | dist
)/
'''

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
