
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-06T14:35:21+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "9b1b1037e54b4e1628aacf28446f981f47c1def4",
 "version": "2021.04.06"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
