
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-13T11:07:02+0800",
 "dirty": true,
 "error": null,
 "full-revisionid": "0a2d01a9cd5831b380e9bc4e76e0d036624912eb",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
