
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "8adb11813712bdfc6fe13612e256b7af24bfdb0b",
 "version": "0.21.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
