#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['vulnerabilities']

package_data = \
{'': ['*']}

setup(name='vulnerabilities',
      version='0.0.1',
      description='Module to manage vulnerabilities',
      author='Damien Carol',
      author_email='damien.carol@gmail.com',
      url='https://github.com/damiencarol/vulnerabilities',
      packages=packages,
      package_data=package_data,
     )
