
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-09T11:24:24+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "bfae1d6722d296650adb9b694b3a08d6cb2f7e88",
 "version": "v0.9.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
