
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-06T15:05:41+0800",
 "dirty": true,
 "error": null,
 "full-revisionid": "93f15091cc79185d2fde8ac9d989c92f99ff82d7",
 "version": "0.0.88.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
