
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-11T20:33:15+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f3c329801589a3c91b43e5b3666deabca5bc6f83",
 "version": "0.0.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
