[build-system]
requires = [ "whey",]
build-backend = "whey"

[project]
name = "repo_helper_github"
version = "0.7.0"
description = "Manage GitHub repositories with repo-helper."
readme = "README.rst"
keywords = [ "github", "repo-helper",]
dynamic = []
dependencies = [
    "click>=7.1.2",
    "consolekit>=1.1.2",
    'cryptography==3.3.2; platform_system != "Linux"',
    "deprecation-alias>=0.1.1",
    "domdf-python-tools>=2.0.0",
    "dulwich!=0.20.7,!=0.20.8,!=0.20.9,>=0.20.5",
    "github3-py>=1.3.0",
    "github3-utils>=0.5.0",
    "pymacaroons>=0.13.0",
    "repo-helper>=2020.12.18",
    "southwark>=0.4.0",
    "typing-extensions>=3.7.4.3",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Topic :: Software Development :: Version Control :: Git",
    "Typing :: Typed",
]
requires-python = ">=3.6"

[[project.authors]]
email = "dominic@davis-foster.co.uk"
name = "Dominic Davis-Foster"


[project.license]
file = "LICENSE"

[project.urls]
Homepage = "https://github.com/repo-helper/repo_helper_github"
"Issue Tracker" = "https://github.com/repo-helper/repo_helper_github/issues"
"Source Code" = "https://github.com/repo-helper/repo_helper_github"
Documentation = "https://repo_helper_github.readthedocs.io/en/latest"

[tool.dep_checker]
allowed_unused = [ "cryptography",]

[tool.mkrecipe]
conda-channels = [ "repo-helper",]
extras = "all"
license-key = "MIT"

[tool.whey]
base-classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Version Control :: Git",
    "Typing :: Typed",
]
python-versions = [ "3.6", "3.7", "3.8", "3.9",]
python-implementations = [ "CPython", "PyPy",]
platforms = [ "Windows", "macOS", "Linux",]
license-key = "MIT"

[project.entry-points."repo_helper.command"]
repo_helper_github = "repo_helper_github.cli:github"

[tool.dep_checker.name_mapping]
github3_py = "github3"
