[tool.poetry]
name = "poetry-tutorial-project-doron"
version = "0.1.0"
description = ""
authors = ["dorhar <doron.harnoy@tensorleap.ai>"]

[tool.poetry.dependencies]
python = "^3.7"
icecream = "^2.1.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
