
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-09T14:55:51-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "1406ddb9328df524ff103b560ea049d392b8be3c",
 "version": "1.75.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
