
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "4adcce020fea9dd8fffe7d17fbd170e3724ab11e",
 "version": "1.1.post11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
