#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup


setup(name='signed_backbones',
      version='0.91.3',
      description='Python package for extracting signed backbones of intrinsically dense weighted networks.',
      author='Furkan Gürsoy',
      author_email='furkan.gursoy@boun.edu.tr',
      url='https://github.com/furkangursoy/signed_backbones',
      py_modules=['signed_backbones'],
     )
