
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-07T20:47:21-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "e8e198e806e46f2160a70f00e64ff6768ee3b5dc",
 "version": "0.1.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
