
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-06T20:21:59-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "5377cb0bfab4919ea572e05ec898c9bb10b6a41a",
 "version": "v0.1+26.g5377cb0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
