
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-12T10:22:04+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "0845332cf4973da1de434675c81c894d2d5974ca",
 "version": "0.7.0.post.dev60"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
