
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-06T10:18:38+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "ac7ac2c691f4b45f182b06adabf6a50f3fc8c715",
 "version": "v0.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
