
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-07T16:42:11+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "2f8cba71ef0f41d2e89ad34a24cd3f6af9bc4ba5",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
