# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: action_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import entity_pb2 as entity__pb2
import action_pb2 as action__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
import integration_source_pb2 as integration__source__pb2
import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='action_service.proto',
  package='calixa.domain.action',
  syntax='proto3',
  serialized_options=b'\n\027io.calixa.domain.actionH\001P\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14\x61\x63tion_service.proto\x12\x14\x63\x61lixa.domain.action\x1a\x0c\x65ntity.proto\x1a\x0c\x61\x63tion.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x18integration_source.proto\x1a\x0c\x63ommon.proto\"\x13\n\x11GetActionsRequest\"C\n\x12GetActionsResponse\x12-\n\x07\x61\x63tions\x18\x01 \x03(\x0b\x32\x1c.calixa.domain.entity.Entity\"\xab\x01\n\x13InvokeActionRequest\x12\x33\n\raction_config\x18\x01 \x01(\x0b\x32\x1c.calixa.domain.entity.Entity\x12\x42\n\x16override_action_params\x18\x02 \x01(\x0b\x32\".calixa.domain.action.ActionParams\x12\x1b\n\x13\x65ntity_canonical_id\x18\x03 \x01(\t\"\xa2\x01\n\x14InvokeActionResponse\x12\x43\n\raction_status\x18\x01 \x01(\x0e\x32,.calixa.domain.action.ActionInvocationStatus\x12\x45\n\x03raw\x18\x02 \x01(\x0b\x32\x38.calixa.domain.action.ThirdPartyActionInvocationResponse2\xd9\x01\n\rActionService\x12\x61\n\nGetActions\x12\'.calixa.domain.action.GetActionsRequest\x1a(.calixa.domain.action.GetActionsResponse0\x01\x12\x65\n\x0cInvokeAction\x12).calixa.domain.action.InvokeActionRequest\x1a*.calixa.domain.action.InvokeActionResponseB\x1d\n\x17io.calixa.domain.actionH\x01P\x01\x62\x06proto3'
  ,
  dependencies=[entity__pb2.DESCRIPTOR,action__pb2.DESCRIPTOR,google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,integration__source__pb2.DESCRIPTOR,common__pb2.DESCRIPTOR,])




_GETACTIONSREQUEST = _descriptor.Descriptor(
  name='GetActionsRequest',
  full_name='calixa.domain.action.GetActionsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=163,
)


_GETACTIONSRESPONSE = _descriptor.Descriptor(
  name='GetActionsResponse',
  full_name='calixa.domain.action.GetActionsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='actions', full_name='calixa.domain.action.GetActionsResponse.actions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=232,
)


_INVOKEACTIONREQUEST = _descriptor.Descriptor(
  name='InvokeActionRequest',
  full_name='calixa.domain.action.InvokeActionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='action_config', full_name='calixa.domain.action.InvokeActionRequest.action_config', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='override_action_params', full_name='calixa.domain.action.InvokeActionRequest.override_action_params', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='entity_canonical_id', full_name='calixa.domain.action.InvokeActionRequest.entity_canonical_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=235,
  serialized_end=406,
)


_INVOKEACTIONRESPONSE = _descriptor.Descriptor(
  name='InvokeActionResponse',
  full_name='calixa.domain.action.InvokeActionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='action_status', full_name='calixa.domain.action.InvokeActionResponse.action_status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='raw', full_name='calixa.domain.action.InvokeActionResponse.raw', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=409,
  serialized_end=571,
)

_GETACTIONSRESPONSE.fields_by_name['actions'].message_type = entity__pb2._ENTITY
_INVOKEACTIONREQUEST.fields_by_name['action_config'].message_type = entity__pb2._ENTITY
_INVOKEACTIONREQUEST.fields_by_name['override_action_params'].message_type = action__pb2._ACTIONPARAMS
_INVOKEACTIONRESPONSE.fields_by_name['action_status'].enum_type = action__pb2._ACTIONINVOCATIONSTATUS
_INVOKEACTIONRESPONSE.fields_by_name['raw'].message_type = action__pb2._THIRDPARTYACTIONINVOCATIONRESPONSE
DESCRIPTOR.message_types_by_name['GetActionsRequest'] = _GETACTIONSREQUEST
DESCRIPTOR.message_types_by_name['GetActionsResponse'] = _GETACTIONSRESPONSE
DESCRIPTOR.message_types_by_name['InvokeActionRequest'] = _INVOKEACTIONREQUEST
DESCRIPTOR.message_types_by_name['InvokeActionResponse'] = _INVOKEACTIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetActionsRequest = _reflection.GeneratedProtocolMessageType('GetActionsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETACTIONSREQUEST,
  '__module__' : 'action_service_pb2'
  # @@protoc_insertion_point(class_scope:calixa.domain.action.GetActionsRequest)
  })
_sym_db.RegisterMessage(GetActionsRequest)

GetActionsResponse = _reflection.GeneratedProtocolMessageType('GetActionsResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETACTIONSRESPONSE,
  '__module__' : 'action_service_pb2'
  # @@protoc_insertion_point(class_scope:calixa.domain.action.GetActionsResponse)
  })
_sym_db.RegisterMessage(GetActionsResponse)

InvokeActionRequest = _reflection.GeneratedProtocolMessageType('InvokeActionRequest', (_message.Message,), {
  'DESCRIPTOR' : _INVOKEACTIONREQUEST,
  '__module__' : 'action_service_pb2'
  # @@protoc_insertion_point(class_scope:calixa.domain.action.InvokeActionRequest)
  })
_sym_db.RegisterMessage(InvokeActionRequest)

InvokeActionResponse = _reflection.GeneratedProtocolMessageType('InvokeActionResponse', (_message.Message,), {
  'DESCRIPTOR' : _INVOKEACTIONRESPONSE,
  '__module__' : 'action_service_pb2'
  # @@protoc_insertion_point(class_scope:calixa.domain.action.InvokeActionResponse)
  })
_sym_db.RegisterMessage(InvokeActionResponse)


DESCRIPTOR._options = None

_ACTIONSERVICE = _descriptor.ServiceDescriptor(
  name='ActionService',
  full_name='calixa.domain.action.ActionService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=574,
  serialized_end=791,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetActions',
    full_name='calixa.domain.action.ActionService.GetActions',
    index=0,
    containing_service=None,
    input_type=_GETACTIONSREQUEST,
    output_type=_GETACTIONSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='InvokeAction',
    full_name='calixa.domain.action.ActionService.InvokeAction',
    index=1,
    containing_service=None,
    input_type=_INVOKEACTIONREQUEST,
    output_type=_INVOKEACTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ACTIONSERVICE)

DESCRIPTOR.services_by_name['ActionService'] = _ACTIONSERVICE

# @@protoc_insertion_point(module_scope)
