
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-10T18:00:17+0800",
 "dirty": true,
 "error": null,
 "full-revisionid": "e29f8fe36a785eafbbbd03bd295f8b6e82c37a34",
 "version": "0.0.90.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
