[tool.poetry]
name = "mcanitexgen"
version = "1.2.3"
description = "An animation generator for Minecraft .mcmeta files"
authors = ["Oran9eUtan <oran9eutan@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/OrangeUtan/mcanitexgen"
repository = "https://github.com/OrangeUtan/mcanitexgen"
keywords = ["minecraft", "animation", "mcmeta"]
include = [
    "LICENSE"
]

[tool.poetry.scripts]
mcanitexgen = "mcanitexgen.__main__:app"

[tool.poetry.dependencies]
python = "^3.8"
typer = "^0.3.2"
Pillow = "^8.1.2"
numpy = "^1.20.1"

[tool.poetry.dev-dependencies]
pre-commit = "^2.10.1"
black = "^20.8b1"
mypy = "^0.812"
hypothesis = "^6.3.4"
pytest = "^6.2.2"
isort = "^5.7.0"
coverage-badge = "^1.0.1"
pytest-cov = "^2.11.1"
python-semantic-release = "^7.15.1"
pytest-insta = "^0.1.7"
beet = "^0.18.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 95

[tool.isort]
line_length = 95

[tool.coverage.run]
source = ["mcanitexgen"]
omit = ["mcanitexgen/__main__.py", "mcanitexgen/gif/images2gif.py"]

[tool.semantic_release]
branch="release"
version_toml = "pyproject.toml:tool.poetry.version"
version_variable = ["mcanitexgen/__init__.py:__version__"]
major_on_zero = false
build_command = "poetry build"
