[tool.poetry]
name = "fantasynames"
version = "0.0.2"
description="A fantasy themed random name generator."
authors = ["Jessica Peck <jessypeck@gmail.com>"]
homepage = "https://github.com/jessypeck/fantasynames"
repository = "https://github.com/jessypeck/fantasynames"

[tool.poetry.dependencies]
python = "^3.7"
black = "^20.8b1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
