
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-06T18:05:45+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "98758bbc65792a56816173f81325b610840cb5e7",
 "version": "2.0.69"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
