
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-10T02:33:31-0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "6a67a2261ee47a5428e52607e1c8d1721636f7b1",
 "version": "0.5.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
