
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-06T05:23:36+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "faa1f2ac573e1154684aea42858fbbd994598c6b",
 "version": "0.7.0.post.dev50"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
