
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-07T09:36:44+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f255ca476daea8ba3afe2707a736b3e9c1b83fab",
 "version": "1.15.0.post.dev146"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
