#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['pykanban']

package_data = \
{'': ['*'], 'pykanban': ['static/*', 'static/styles/*', 'templates/*']}

setup(name='pykanban',
      version='0.1.0',
      description='Initializing flask project ',
      author='Lucca Bertoncini',
      author_email='luccabazzo@gmail.com',
      url='https://github.com/luccabb/flask_kanban',
      packages=packages,
      package_data=package_data,
     )
