[tool.poetry]
name = "EasyPyRequests"
version = "1.0.0"
description = "Requests Library for easy format"
authors = ["DragonWolf <officialdragonwolf@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
