
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-05T19:30:37-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "2529a6b53ccaa90c316cca9f24bfcf9b3bc59019",
 "version": "v1.2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
