
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-07T10:28:20+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "30be435cb5e13dda38379dbc3a60c3180751ef2d",
 "version": "1.15.0.post.dev150"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
