
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-06T14:42:34-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "6b6b82764d988a8c0a7f275868fc7c8a69b3cadf",
 "version": "0.9.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
