[tool.poetry]
name = "knightstour"
version = "0.1.1"
description = "A simplistic implementation of the knights tour"
authors = ["Lucas McGregor <lucasmcgregor@gmail.com>"]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
