
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-03T18:36:16+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "b043ad81fc44ed6e53ba778ff6b40927110bd683",
 "version": "1.0.21"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
