
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-10T16:56:37+0800",
 "dirty": true,
 "error": null,
 "full-revisionid": "555e3107702189bfc73e24f2ca408b28433d07a1",
 "version": "0.0.90.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
