
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-08T10:18:31+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "5c2b663314d6bd337eb601afb378927468fc9a5e",
 "version": "4.24"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
