
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-05T13:33:33+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "18fffef4049eec754ee51bbecb2af266d9128cd5",
 "version": "0.0.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
