# coding: utf-8

"""
    bmlx api-server.

    Documentation of bmlx api-server apis. To find more info about generating spec from source, please refer to https://goswagger.io/use/spec.html  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import bmlx_openapi_client
from bmlx_openapi_client.models.trigger_version_request import TriggerVersionRequest  # noqa: E501
from bmlx_openapi_client.rest import ApiException

class TestTriggerVersionRequest(unittest.TestCase):
    """TriggerVersionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TriggerVersionRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = bmlx_openapi_client.models.trigger_version_request.TriggerVersionRequest()  # noqa: E501
        if include_optional :
            return TriggerVersionRequest(
                exp_id = 56, 
                id = 56, 
                parameters = {
                    'key' : '0'
                    }, 
                run_name = '0'
            )
        else :
            return TriggerVersionRequest(
        )

    def testTriggerVersionRequest(self):
        """Test TriggerVersionRequest"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
