# coding: utf-8

"""
    bmlx api-server.

    Documentation of bmlx api-server apis. To find more info about generating spec from source, please refer to https://goswagger.io/use/spec.html  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import bmlx_openapi_client
from bmlx_openapi_client.models.get_versions_response import GetVersionsResponse  # noqa: E501
from bmlx_openapi_client.rest import ApiException

class TestGetVersionsResponse(unittest.TestCase):
    """GetVersionsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test GetVersionsResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = bmlx_openapi_client.models.get_versions_response.GetVersionsResponse()  # noqa: E501
        if include_optional :
            return GetVersionsResponse(
                experiment_versions = [
                    bmlx_openapi_client.models.experiment_version.ExperimentVersion(
                        create_time = 56, 
                        cron_workflow_name = '0', 
                        dag = [
                            bmlx_openapi_client.models.node.Node(
                                children = [
                                    '0'
                                    ], 
                                component = '0', 
                                exec_properties = {
                                    'key' : '0'
                                    }, 
                                inputs = [
                                    bmlx_openapi_client.models.node_io.NodeIO(
                                        name = '0', 
                                        type = '0', )
                                    ], 
                                outputs = [
                                    bmlx_openapi_client.models.node_io.NodeIO(
                                        name = '0', 
                                        type = '0', )
                                    ], )
                            ], 
                        db_status = 56, 
                        deployment_running = True, 
                        description = '0', 
                        execute_detail = '0', 
                        experiment_id = 56, 
                        id = 56, 
                        name = '0', 
                        namespace = '0', 
                        owner = '0', 
                        package_checksum = '0', 
                        package_uri = '0', 
                        parameters = {
                            'key' : '0'
                            }, 
                        pipeline_version_id = 56, 
                        resource_group = '0', 
                        status = 'Deactivated', 
                        trigger_instantly = True, 
                        trigger_type = 'Manual-Trigger', )
                    ], 
                next_page_token = '0'
            )
        else :
            return GetVersionsResponse(
        )

    def testGetVersionsResponse(self):
        """Test GetVersionsResponse"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
