
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-07T10:23:48+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "31a1487d8657cf62265123906f020630b53ed18e",
 "version": "1.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
