name: ci

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - uses: actions/checkout@v2
    - run: |
        pip install sphinx
        make doc

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - uses: actions/checkout@v2
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .
    - name: Lint with black
      run: |
        pip install black
        black --check .

  build:
    runs-on: ubuntu-20.04  # ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - uses: actions/checkout@v2
    - name: Install gmsh
      run: |
        sudo apt-get install -y python3-gmsh
    - name: Test with tox
      run: |
        pip install tox
        tox
    - uses: codecov/codecov-action@v1
      if: ${{ matrix.python-version == '3.8' }}
