[tool.poetry]
name = "testfinder"
version = "0.0.1"
description = "Find test cases on a Python project."
authors = ["Sid Mitra <testfinder@sidmitra.com>"]
license = "MIT"
readme = "README.md"
keywords = ["pytest", "django", "testing"]

[tool.poetry.dependencies]
python = "^3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
