
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-09T20:58:54+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "70982ccce0bfaaf63ee8c023ec081aed1d9c0124",
 "version": "0.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
