
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-11T12:00:52+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "ab5761115f57e64d635fe94ef0a29f0946a66d00",
 "version": "0.0.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
