
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-06T15:34:29-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "abdfc7980fe5f30ef6109f020e185be7ad551e39",
 "version": "v2.1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
