[build-system]
requires = ["flit_core >=2,<4", "pydantic>=1.8.1", "levenshtein>=0.12.0"]
requires-python = ">=3.7"
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "domainrules"
author = "Svyatoslav"
author-email = "svyatka@gmail.com"
home-page = "https://github.com/Svyat33/domain_rules"
classifiers = [ "License :: OSI Approved :: MIT License",]
description-file = "README.md"

