# Version file autogenerated by the build process
version = '0.8.5'
build = '654'
vcs_info = 'Git SHA1 1427def7 committed on 2021-04-07'

if __name__ == '__main__':
    print('KSCONF_VERSION="0.8.5"\nKSCONF_BUILD="654"\nKSCONF_VCS_INFO="Git SHA1 1427def7 committed on 2021-04-07"')
