
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-07T10:50:57+0800",
 "dirty": true,
 "error": null,
 "full-revisionid": "64d866edeb875afd22654c4ba983dfbaa9afa59e",
 "version": "0.0.89.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
