#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['json2mqtt']

package_data = \
{'': ['*']}

install_requires = \
['jmespath',
 'jsonschema',
 'multitimer',
 'paho-mqtt',
 'pid',
 'requests',
 'rfc3986-validator',
 'ruamel.yaml']

extras_require = \
{'test': ['pytest', 'pytest-cov', 'pyproject-flake8', 'mock']}

entry_points = \
{'console_scripts': ['json2mqtt = json2mqtt.__main__:main']}

setup(name='json2mqtt',
      version='0.0.2',
      description='Json2MQTT: A simple python daemon that crawls json apis and sends a selection of the data to a MQTT broker',
      author='Flip Hess',
      author_email='flip@fliphess.com',
      url='https://github.com/fliphess/json2mqtt',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      entry_points=entry_points,
      python_requires='>=3.7',
     )
