
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-07T12:29:46+0800",
 "dirty": true,
 "error": null,
 "full-revisionid": "73ad69156131ff9807ec010e20cbf991a1dc7e19",
 "version": "0.0.89.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
