
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-12T22:37:36+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "337ed78dc7c69125f43d913c8ff9b6177295c99e",
 "version": "0.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
