
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-12T14:49:43-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "619a7531b6d6d278fce7b71cbdb2ad6a18baafd3",
 "version": "v2.0alpha21"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
