
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-08T01:25:22-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "4add0661b5982fe912529f685911c0ada5fe01fc",
 "version": "0.3.34"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
