# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ConnectionError": "00_core.ipynb",
         "CredentialsError": "00_core.ipynb",
         "SQLError": "00_core.ipynb",
         "UseDatabase": "00_core.ipynb"}

modules = ["DBcm.py"]

doc_url = "https://barrypj.github.io/DBcm/"

git_url = "https://github.com/barrypj/DBcm/tree/master/"

def custom_doc_links(name): return None
