
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-05T09:35:35-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "be5cfea9b6d306013122c1fff3d2cbab67e7fdc7",
 "version": "4.3.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
