
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-12T18:23:37+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "5dd26000f87c135e8b4e3b2aabf8eddd37740e5c",
 "version": "2.0.72"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
