#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['getitdone']

package_data = \
{'': ['*']}

setup(name='getitdone',
      version='0.0.4',
      description="`getitdone` to-do list application... Let's make some lists!",
      author='Ryan Butler',
      author_email='ryanleonbutler@gmail.com',
      url='https://github.com/ryanleonbutler/getitdone',
      packages=packages,
      package_data=package_data,
      python_requires='>=3.7',
     )
