
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-10T21:42:40-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "73e9bf022602620b7a9795b3ad0ea6ffa93eb31a",
 "version": "2.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
