
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-12T09:56:56+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "3d92a1bec9ff95a74d95ebc7f8b73972b18dd83a",
 "version": "0.7.0.post.dev58"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
