
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-09T16:29:32+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "5dad3a3b0da88082fb730051275f8b09c39efc41",
 "version": "2.0.70"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
