name: test_env_cmip6_preprocessing
channels:
  - conda-forge
dependencies:
  - python=3.8
  - xarray
  - xgcm
  - pyproj
  - cftime
  - matplotlib
  - regionmask
  - pytest-cov
  - pytest-xdist
  - codecov
