[tool.poetry]
name = "stb-automator"
version = "0.1.0"
description = "A library for automated control & testing of set-top boxes"
authors = ["Eugene Triguba <eugenetriguba@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/eugenetriguba/stb-automator"
keywords = [
    "set-top box",
    "test automation",
    "opencv",
    "tesseract",
    "LIRC",
    "gstreamer"
]
classifiers = [
    "Development Status :: 1 - Planning",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Topic :: Software Development :: Testing",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
packages = [{ include = "stb" }]

[tool.taskipy.tasks]
lint = "pre-commit run --all"
test = "poetry run task test_unit"
test_ci = "task test -- --cov-report=xml"
test_unit = "poetry run pytest -vvv --cov=stb/ --cov-report term-missing tests/"

[tool.poetry.scripts]
stb = 'stb.cli.runner:stb'

[tool.poetry.dependencies]
python = "^3.7"
click = "^7.1.2"
opencv-python = "^4.5.1"
config-file = { version = "^0.12.0", extras = ["toml"] }
PyGObject = "^3.40.0"
numpy = "^1.20.2"
pytesseract = "^0.3.7"
lirc = "^1.0.1"

[tool.poetry.dev-dependencies]
pre-commit = "^2.9.0"
flake8 = "^3.9.0"
isort = "^5.8.0"
seed-isort-config = "^2.2.0"
pytest = "^6.2.0"
pytest-cov = "^2.10.0"
bump2version = "^1.0.0"
taskipy = "^1.7.0"
black = "^20.8b1"
sphinx = "^3.5.3"
sphinx_rtd_theme = "^0.5.1"


[tool.black]
target_version = ['py37']
include = '\.pyi?$'

[tool.isort]
known_first_party = ["stb"]
known_third_party = ["click", "config_file", "gi", "lirc", "numpy", "pytest"]

# Black/isort Compatibility
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88

[build-system]
requires = ["poetry>=1.1", "wheel", "setuptools"]
build-backend = "poetry.masonry.api"
