
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "75f10fb4d541fabd21054c21e2d5ed90a152cf2a",
 "version": "1.19.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
