
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-03T21:20:01-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "42eb1dad4f19e7e01d86fe46d5167bd5c43243ea",
 "version": "v1.1.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
