
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-12T16:19:48+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "731a885e9d42ebd382e1a62c7a1aacf314f014ff",
 "version": "2.0.71"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
