
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-06T07:57:54-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "44a4b3d71b43397be13565e4232527c568545e55",
 "version": "4.1.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
