
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-07T15:43:50-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "d0d0c1ae6af17c37f93b6b86cf88cda29fee5916",
 "version": "v1.0.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
