[tool.poetry]
name = "xscrapers"
version = "0.0.7"
description = "A simple webscraper library"
license = "MIT"
authors = ["Julian Stang <julian.stang@tum.de>"]
readme = "README.md"
repository = "https://github.com/juliandwain/xscrapers"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.25.1"
selenium = "^3.141.0"
fake-useragent = "^0.1.11"
html5lib = "^1.1"
numpy = "^1.20.2"
pandas = "^1.2.3"
beautifulsoup4 = "^4.9.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
