name: Publish Python 🐍 wheel distributions 📦 to PyPI and TestPyPI(mac/win)

on:
  push:
    branches:
      - main
      - releases/*
    tags:
      - v*

jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI and TestPyPI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 20
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependency
      run: python -m pip install build twine
    - name: Build a wheel package
      run: python -m build --wheel .
    - name: Publish distribution 📦 to Test PyPI
      if: startsWith(github.event.ref, 'refs/heads/main')
      run: python -m twine upload dist/*.whl
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.testpypi_password }}
        TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
        TWINE_NON_INTERACTIVE: 1
    - name: Publish distribution 📦 to PyPI
      if: startsWith(github.event.ref, 'refs/tags')
      run: python -m twine upload dist/*.whl
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.pypi_password }}
        TWINE_NON_INTERACTIVE: 1
