# Version file autogenerated by the build process
version = '0.8.5rc1'
build = '652'
vcs_info = 'Git SHA1 e8d29e6d committed on 2021-04-07'

if __name__ == '__main__':
    print('KSCONF_VERSION="0.8.5rc1"\nKSCONF_BUILD="652"\nKSCONF_VCS_INFO="Git SHA1 e8d29e6d committed on 2021-04-07"')
