name: test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - ver/*
    tags:
      - v*

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Update pip
      run: pip install -U pip
    - name: Install package
      run: |
        apt-get update && apt-get install -y git
        pip --no-cache-dir install .
    - name: Lint with black
      run: |
        pip install black
        black --check src/
    - name: Test with pytest
      run: |
        pip install -r tests/requirements.txt
        pytest -vvra --cov seddy --cov-report xml --cov-report term
    - name: Upload coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
