
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-10T22:48:54-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "8ecc36679980cf712284c5e07d96c57cb1fa14d0",
 "version": "v0.1.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
