[tool.poetry]
name = "iscc-index"
version = "1.1.0b5"
description = "ISCC Index - Nearest Neighbor Search"
authors = ["Titusz Pan <tp@py7.de>"]
readme = "README.md"
homepage = "https://iscc.codes/"

[tool.poetry.scripts]
iscc-index = 'iscc_index.main:run_server'

[tool.poetry.dependencies]
python = ">=3.6.1,<3.10"
fastapi = "^0.63.0"
iscc = {version = "^1.1.0b5", allow-prereleases = true}
uvicorn = "^0.13.4"

[tool.poetry.dev-dependencies]
pytest = "^6.2.3"
black = {version = "19.10b0", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
