
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-05T14:49:30-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "5b1bf61a8f92438aa2066aeb7fd0935f80d51851",
 "version": "1.1.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
