
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-06T01:39:56+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "71dbf36fafdbcd66869e6852d0213917145e4e89",
 "version": "2.3.1rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
