
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-02T12:33:54+0800",
 "dirty": true,
 "error": null,
 "full-revisionid": "524f71c1ed8ca6436faa45d748341e0bb0ae82c5",
 "version": "0.0.88.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
