
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-10T16:36:12+0800",
 "dirty": true,
 "error": null,
 "full-revisionid": "efba222090d030a794c82ff70d0ab1671e0825e1",
 "version": "0.0.90.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
