[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
target-version = ["py36", "py37", "py38"]
include = "\\.pyi?$"

[tool.isort]
profile = "black"
line_length = 100

[tool.poetry]
name = "spiel"
version = "0.1.0"
description = "A framework for building and presenting richly-styled presentations in your terminal using Python."
authors = ["JoshKarpel <josh.karpel@gmail.com>"]
license = "MIT"
include = ["demo/*"]

[tool.poetry.dependencies]
python = "^3.9"
rich = "^10.0.0"
typer = "^0.3.2"
watchdog = "^2.0.2"
pendulum = "^2.1.2"
Pillow = "^8.2.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
pytest-watch = "^4.2.0"
pytest-cov = "^2.11.1"
pytest-xdist = "^2.2.1"
mypy = "^0.812"
pytest-mypy = "^0.8.1"
pytest-mock = "^3.5.1"
hypothesis = "^6.8.3"

[tool.poetry.scripts]
spiel = 'spiel.main:app'

[tool.pytest.ini_options]
addopts = ['--strict-markers', '--mypy']
testpaths = ["tests", "spiel"]
norecursedirs = ["demo"]
