
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-09T15:40:00+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "944c38bbbb439e12cdea44dda014ab591af1cfbf",
 "version": "2434"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
