
# This file was generated by '_versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-08T02:39:24-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "d0a813f9ed087236a68672ef15aa460d2bbecd8e",
 "version": "1.2.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
