
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-03T19:33:36+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d5ebdaaa6ddbbddadfe15517f88d371b8d9329f6",
 "version": "0.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
