
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-07T18:58:51-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "d026b30d0c384526636739b31fd781133a175efe",
 "version": "4.5.24"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
