
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-12T15:42:55-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "88bff4b0e1f4d28466dfe49be45dfcbf52b57d8c",
 "version": "1.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
