
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-11T18:40:23-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "1c0f503d6fca1eeb976f7f4e9cb54a3bfc150d61",
 "version": "v0.4.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
