
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-07T17:29:14+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "7eeadef989003a6d4fd07d9849b11df9b941397b",
 "version": "v2.2.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
