#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['nxfvars', 'nxfvars.tests']

package_data = \
{'': ['*'], 'nxfvars.tests': ['testdata/*']}

install_requires = \
['pytoml', 'pyyaml', 'jupytext', 'nbconvert>=4.2', 'ipykernel']

extras_require = \
{'test': ['pytest', 'black']}

entry_points = \
{'console_scripts': ['nxfvars = nxfvars.cli:main']}

setup(name='nxfvars',
      version='0.2',
      description='Access nextflow variables from Python',
      author='Gregor Sturm',
      author_email='gregor.sturm@i-med.ac.at',
      url='https://github.com/grst/nxfvars',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      entry_points=entry_points,
      python_requires='>= 3.8',
     )
