
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-11T02:23:32+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "c9990b040832792aa897b27a07180d4629cb8de3",
 "version": "0.5.dev2115"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
