
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-04T02:24:49+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d6faa335662624c95e0ada2fcfe803ca1397f4a4",
 "version": "0.5.dev2114"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
