
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-11T15:49:15+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "469bb0fc7f01a89ac3614c5395ef6c6a54c2e9f1",
 "version": "0.0.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
