# Generated by Django 2.2.19 on 2021-03-15 10:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30, verbose_name='Наименование товара')),
                ('shelf_life', models.DurationField(verbose_name='Срок годности')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_delivery', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время привоза на склад')),
                ('date_of_manufacture', models.DateField(verbose_name='Дата создания товара')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tests.Product', verbose_name='Товар')),
            ],
        ),
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_add', models.DateField(default=datetime.datetime.now, verbose_name='Дата добавления продукта в каталог')),
                ('storage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tests.Storage', verbose_name='Товар на складе')),
            ],
        ),
    ]
