
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-12T21:12:31+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "ea9a2f5c8b8474bcec3fa82eb806f43ecfc5b473",
 "version": "0.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
