#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['icedtools']

package_data = \
{'': ['*']}

setup(name='icedtools',
      version='0.0.1',
      description="Let's write some code",
      author='Ivica Ceraj',
      author_email='iceraj@gmail.com',
      url='https://github.com/iceraj/icedtools',
      packages=packages,
      package_data=package_data,
     )
