info = {"message": "Updates for relative URLs (#752)", "commit": "71278b0b727bc103f408fe3c279c5487f44fee56", "date": "2021-04-05 11:30:54 -0700", "branch": "master", "version": "1.0.0+87.g71278b0b"}

# This file is automatically generated by version.py
# Do not include it to git!
