
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-08T02:39:11-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "1500c3bbc9d69a4e6f12e4f6442b548e60072f15",
 "version": "v1.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
