#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['domainrules']

package_data = \
{'': ['*']}

setup(name='domainrules',
      version='0.1.5',
      description="Let's describe alowed rules!",
      author='Svyatoslav',
      author_email='svyatka@gmail.com',
      url='https://github.com/Svyat33/domain_rules',
      packages=packages,
      package_data=package_data,
     )
