[tool.poetry]
name = "pysoundtool"
version = "0.1.0.a2"
description = "Framework for working with sound in the context of deep learning."
authors = ["a-n-rose <rose.aislyn.noelle@gmail.com>"]
license = "AGPL-3.0"

[tool.poetry.dependencies]
python = "^3.6.9"
setuptools = "^49.3.0"
tensorflow = "2.1.0"
numpy = "^1.19.1"
scipy = "^1.4.1"
scikit-learn = "^0.23.2"
librosa = "0.8.0"
python-speech-features = "0.6"
matplotlib = "3.3.0"
soundfile = "0.10.3.post1"
numba = "0.50.1"
tensorflow-estimator = "^2.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
