
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-06T13:17:12+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "27d45e10b3ff718b0e27e380533fbd1d5e389782",
 "version": "1.0.4rc3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
