
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-08T13:04:59+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "7e3b81128cccf1da245ca90a928b1097ab5155e9",
 "version": "0.7.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
