# Generated by Django 3.1 on 2021-02-25 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conectividadeapp', '0002_auto_20210126_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityremove',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='activityremove',
            name='device',
        ),
        migrations.RemoveField(
            model_name='activityremove',
            name='main_activity',
        ),
        migrations.RemoveField(
            model_name='activityremove',
            name='olddevice',
        ),
        migrations.RemoveField(
            model_name='activityremove',
            name='reason',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='is_active',
            new_name='_active',
        ),
        migrations.RenameField(
            model_name='activityhistory',
            old_name='is_active',
            new_name='_active',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='is_active',
            new_name='_active',
        ),
        migrations.RenameField(
            model_name='actorhistory',
            old_name='is_active',
            new_name='_active',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='type',
        ),
        migrations.RemoveField(
            model_name='activityhistory',
            name='type',
        ),
        migrations.AddField(
            model_name='activityreason',
            name='_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conectividadeapp.activityreason'),
        ),
        migrations.DeleteModel(
            name='ActivityInstall',
        ),
        migrations.DeleteModel(
            name='ActivityRemove',
        ),
    ]
