#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['clmystes_podsearch']

package_data = \
{'': ['*']}

setup(name='clmystes_podsearch',
      version='0.1.0',
      description="Let's find some podcasts!",
      author='clmystes',
      author_email='clmystes@gmail.com',
      url='https://github.com/clmystes/podsearch',
      packages=packages,
      package_data=package_data,
     )
