[tool.poetry]
name = "dotcoin"
version = "0.1.0"
description = ""
authors = ["Orlando Ospino Sánchez <oroschz@outlook.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/oroschz/dotcoin"

[tool.poetry.dependencies]
python = "^3.7"
ccxt = "^1.47.3"
six = "^1.15.0"
beautifultable = "^1.0.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
"dotcoin" = "dotcoin.__main__:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
